import '../styles/tailwind.scss';
import '../styles/global.scss';
import '../../envConfig.ts'
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
export const metadata = {
  title: 'KinU',
  favicon: '/icons/logo.svg',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <meta charSet="utf-8" />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1, shrink-to-fit=no"
        />
        <meta name="description" content={metadata.description} />
        <title>{metadata.title}</title>
        <link rel="icon" href={metadata.favicon} />
      </head>
      <ToastContainer />
      <body>{children}</body>
    </html>
  )
}
